Book.destroy_all

book1 = Book.create :isbn => "9781680501711", :title => "Agile Web Development with Rails 5", :author => "Sam Ruby", :publisher => "Pragmatic Bookshelf", :date_published => "2016", :description => "Rails 5 and Ruby 2.2 bring many improvements, including new APIs and substantial performance enhancements, and the fifth edition of this award-winning classic is now updated! If you're new to Rails, you'll get step-by-step guidance. If you're an experienced developer, this book will give you the comprehensive, insider information you need for the latest version of Ruby on Rails.", :img_url => "https://books.google.com.au/books/content?id=ySyjDAEACAAJ&printsec=frontcover&img=1&zoom=1&imgtk=AFLRE729ScXGYBwXdU9pD35pCjFtTrvPr0yxmBV3kEWosixhChOoRI7l9jUhQPxQIy2Zt8qmz9nwDTs988X_hRqIUttT-DtKwHIOu56JYo1p5_C_jdUJDHwaMTW3nqTE8a7zzTRvVmZT", :status => "Available"

book2 = Book.create :isbn => "9781449360788", :title => "Functional JavaScript: Introducing Functional Programming with Underscore.js", :author => "Michael Fogus", :publisher => "O'Reilly Media, Inc.", :date_published => "2013", :description => "How can you overcome JavaScript language oddities and unsafe features? With this book, you’ll learn how to create code that’s beautiful, safe, and simple to understand and test by using JavaScript’s functional programming support. Author Michael Fogus shows you how to apply functional-style concepts with Underscore.js, a JavaScript library that facilitates functional programming techniques.", :img_url => "https://books.google.com.au/books/content?id=OIhuxqUO2TcC&printsec=frontcover&img=1&zoom=1&edge=curl&imgtk=AFLRE721GnXpSp8NirRfuVs4OaobKc8fL5o_Js3IJyF0zzC_43CxECpSFVbMlocSgBgFZZ6PRR8UJU7UqUlt5P8ekq7Hj8J7YR4yWCIg07n7_7btBC4B80ZO_AhHVNQfihhfHeC07u2e", :status => "Available"

book3 = Book.create :isbn => "9781449360788", :title => "Functional JavaScript: Introducing Functional Programming with Underscore.js", :author => "Michael Fogus", :publisher => "O'Reilly Media, Inc.", :date_published => "2013", :description => "How can you overcome JavaScript language oddities and unsafe features? With this book, you’ll learn how to create code that’s beautiful, safe, and simple to understand and test by using JavaScript’s functional programming support. Author Michael Fogus shows you how to apply functional-style concepts with Underscore.js, a JavaScript library that facilitates functional programming techniques.", :img_url => "https://books.google.com.au/books/content?id=OIhuxqUO2TcC&printsec=frontcover&img=1&zoom=1&edge=curl&imgtk=AFLRE721GnXpSp8NirRfuVs4OaobKc8fL5o_Js3IJyF0zzC_43CxECpSFVbMlocSgBgFZZ6PRR8UJU7UqUlt5P8ekq7Hj8J7YR4yWCIg07n7_7btBC4B80ZO_AhHVNQfihhfHeC07u2e", :status => "Available"

book4 = Book.create :isbn => "9780262560993", :title => "The Little Schemer", :author => "Daniel P. Friedman, Matthias Felleisen", :publisher => "MIT Press", :date_published => "1996", :description => "I learned more about LISP from this book than I have from any of the other LISP books I've read over the years. . . . While other books will tell you the mechanics of LISP, they can leave you largely uninformed on the style of problem-solving for which LISP is optimized. The Little LISPer teaches you how to think in the LISP language. . . an inexpensive, enjoyable introduction.", :img_url => "https://books.google.com.au/books/content?id=xyO-KLexVnMC&printsec=frontcover&img=1&zoom=1&edge=curl&imgtk=AFLRE73d6HD3Nf6Sc5t8MR-J3zLZBQvczJUHf0ywNZsfiQTgh3sFLPIg9RAu8LG5BKLOVZG5NgzodS4wWbTVCiqZv81KwI8c3alOgqwcPHYag_3Z-NcQ1xpaOTnsYnzfiObMgbDFMGdw", :status => "Available"

book5 = Book.create :isbn => "9780199724574", :title => "Complexity: A Guided Tour", :author => "Melanie Mitchell", :publisher => "Oxford University Press", :date_published => "2009", :description => "What enables individually simple insects like ants to act with such precision and purpose as a group? How do trillions of neurons produce something as extraordinarily complex as consciousness? In this remarkably clear and companionable book, leading complex systems scientist Melanie Mitchell provides an intimate tour of the sciences of complexity, a broad set of efforts that seek to explain how large-scale complex, organized, and adaptive behavior can emerge from simple interactions among myriad individuals. Based on her work at the Santa Fe Institute and drawing on its interdisciplinary strategies, Mitchell brings clarity to the workings of complexity across a broad range of biological, technological, and social phenomena, seeking out the general principles or laws that apply to all of them. Richly illustrated, Complexity: A Guided Tour--winner of the 2010 Phi Beta Kappa Book Award in Science--offers a wide-ranging overview of the ideas underlying complex systems science, the current research at the forefront of this field, and the prospects for its contribution to solving some of the most important scientific questions of our time.", :img_url => "https://books.google.com.au/books/content?id=j-PQCwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&imgtk=AFLRE72GQGKtr7vZ3In6YvL5BtCM9g6hKrWlkdZesAADgoOZqYesEjoJtGJIFlKLUuhGa-qxPa4VQ_YZe9f-rKzJVWfq8q6crb4XgguoKG6NU8E-Iux2ttoUUXvNYh1BXlndFVSWVLwc", :status => "Available"

book6 = Book.create :isbn => "9780140289206", :title => "Gödel, Escher, Bach: An Eternal Golden Braid", :author => "Douglas R. Hofstadter", :publisher => "Penguin", :date_published => "2000", :description => "'What is a self, and how can a self come out of inaminate matter?' This is the riddle that drove Hofstadter to write this extraordinary book. Linking together the music of J.S. Bach, the graphic art of Escher and the mathematical theorems of Godel, as well as ideas drawn from logic, biology, psychology, physics and linguistics, Douglas Hofstadter illuminates one of the greatest mysteries of modern science: the nature of human thought processes. 'Every few decades an unknown author brings outa book of such depth, clarity, range, wit, beauty and originality that it is recognized at once as a major literary event. This is such a work' - Martin Gardner", :img_url => "https://books.google.com.au/books/content?id=grzEQgAACAAJ&printsec=frontcover&img=1&zoom=1&imgtk=AFLRE70UMZ4zDjpe_E_KWiSRbqQsEv6t1ixKE4jSDIXy6rYoipTxRcpPnMUDOoaJQpeNzS0jJSPuLGAosQAsJ1ZWNSf7-fWql3q-WKotp0GGoLsEgxTXlgVL4ADqLbuX5fqc9XHGSxLV", :status => "Available"

book7 = Book.create :isbn => "9780140289206", :title => "Gödel, Escher, Bach: An Eternal Golden Braid", :author => "Douglas R. Hofstadter", :publisher => "Penguin", :date_published => "2000", :description => "'What is a self, and how can a self come out of inaminate matter?' This is the riddle that drove Hofstadter to write this extraordinary book. Linking together the music of J.S. Bach, the graphic art of Escher and the mathematical theorems of Godel, as well as ideas drawn from logic, biology, psychology, physics and linguistics, Douglas Hofstadter illuminates one of the greatest mysteries of modern science: the nature of human thought processes. 'Every few decades an unknown author brings outa book of such depth, clarity, range, wit, beauty and originality that it is recognized at once as a major literary event. This is such a work' - Martin Gardner", :img_url => "https://books.google.com.au/books/content?id=grzEQgAACAAJ&printsec=frontcover&img=1&zoom=1&imgtk=AFLRE70UMZ4zDjpe_E_KWiSRbqQsEv6t1ixKE4jSDIXy6rYoipTxRcpPnMUDOoaJQpeNzS0jJSPuLGAosQAsJ1ZWNSf7-fWql3q-WKotp0GGoLsEgxTXlgVL4ADqLbuX5fqc9XHGSxLV", :status => "Available"

book8 = Book.create :isbn => "9780596554873", :title => "JavaScript: The Good Parts: The Good Parts", :author => "Douglas Crockford", :publisher => "O'Reilly Media, Inc.", :date_published => "2008", :description => "Most programming languages contain good and bad parts, but JavaScript has more than its share of the bad, having been developed and released in a hurry before it could be refined. This authoritative book scrapes away these bad features to reveal a subset of JavaScript that's more reliable, readable, and maintainable than the language as a whole—a subset you can use to create truly extensible and efficient code.", :img_url => "https://books.google.com.au/books/content?id=PXa2bby0oQ0C&printsec=frontcover&img=1&zoom=1&edge=curl&imgtk=AFLRE722AjJE15txFoKk8pu6d8BqpOAtMzMYyBUMd0SDVtn8Jstl5aKnkWL_OxWTN4rvIRdV09Di86Hi7FihqESw8b8g2RDkG62dOK1uws50LCCm7Fx4NbtHk-A2yykhsYoTkpUA2CUf", :status => "Available"

book9 = Book.create :isbn => "9781593277574", :title => "Understanding ECMAScript 6: The Definitive Guide for JavaScript Developers", :author => "Nicholas C. Zakas", :publisher => "No Starch Press", :date_published => "2016", :description => "ECMAScript 6 represents the biggest update to the core of JavaScript in the history of the language. In Understanding ECMAScript 6, expert developer Nicholas C. Zakas provides a complete guide to the object types, syntax, and other exciting changes that ECMAScript 6 brings to JavaScript. Every chapter is packed with example code that works in any JavaScript environment so you’ll be able to see new features in action. You’ll learn:

*How ECMAScript 6 class syntax relates to more familiar JavaScript concepts
*What makes iterators and generators useful
*How arrow functions differ from regular functions
*Ways to store data with sets, maps, and more
*The power of inheritance
*How to improve asynchronous programming with promises
*How modules change the way you organize code

Whether you’re a web developer or a Node.js developer, you’ll find Understanding ECMAScript 6 indispensable on your journey from ECMAScript 5 to ECMAScript 6.", :img_url => "https://books.google.com.au/books/content?id=6Ze7DQAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&imgtk=AFLRE719CxgfhmfZyupAvuHOckLJNZNPACU9WKXZJfpngC0xfzru7uzFTW-7uPtiGrT7AguHjmE2WmJp3Mx2Vq0Y6-b9HmA9C1co_EUi0mdI5JhVYD0VKIJK4k2DSv9-z61qd3A8mJLg", :status => "Available"

book10 = Book.create :isbn => "9781934356371", :title => "The RSpec Book: Behaviour-driven Development with RSpec, Cucumber, and Friends", :author => "David Chelimsky", :publisher => "Pragmatic Bookshelf", :date_published => "2010", :description => "Behaviour-Driven Development (BDD) gives you the best of Test Driven Development, Domain Driven Design, and Acceptance Test Driven Planning techniques, so you can create better software with self-documenting, executable tests that bring users and developers together with a common language.

Get the most out of BDD in Ruby with The RSpec Book, written by the lead developer of RSpec, David Chelimsky.

You'll get started right away with RSpec 2 and Cucumber by developing a simple game, using Cucumber to express high-level requirements in language your customer understands, and RSpec to express more granular requirements that focus on the behavior of individual objects in the system. You'll learn how to use test doubles (mocks and stubs) to control the environment and focus the RSpec examples on one object at a time, and how to customize RSpec to 'speak' in the language of your domain.

You'll develop Rails 3 applications and use companion tools such as Webrat and Selenium to express requirements for web applications both in memory and in the browser. And you'll learn to specify Rails views, controllers, and models, each in complete isolation from the other.

Whether you're developing applications, frameworks, or the libraries that power them, The RSpec Book will help you write better code, better tests, and deliver better software to happier users.", :img_url => "https://books.google.com.au/books/content?id=0rxoPgAACAAJ&printsec=frontcover&img=1&zoom=1&imgtk=AFLRE701S3bRyEp4ikwehSGBm3KQNlPIvjGa6iPT80OuSiUo2TeF_Y2mgtYV_YGoo2q65TRDN5fjzyVBgNJgJCZSExpUeqxBG6MjDPddfrz6UZ-PGRZPJ-9bBveoAMGsFGDNybH0hbdq", :status => "Available"

book11 = Book.create :isbn => "9780596553968", :title => "The Cathedral & the Bazaar: Musings on Linux and Open Source by an Accidental Revolutionary", :author => "Eric S. Raymond", :publisher => "O'Reilly Media, Inc.", :date_published => "2001", :description => "Open source provides the competitive advantage in the Internet Age. According to the August Forrester Report, 56 percent of IT managers interviewed at Global 2,500 companies are already using some type of open source software in their infrastructure and another 6 percent will install it in the next two years. This revolutionary model for collaborative software development is being embraced and studied by many of the biggest players in the high-tech industry, from Sun Microsystems to IBM to Intel.The Cathedral & the Bazaar is a must for anyone who cares about the future of the computer industry or the dynamics of the information economy. Already, billions of dollars have been made and lost based on the ideas in this book. Its conclusions will be studied, debated, and implemented for years to come. According to Bob Young, 'This is Eric Raymond's great contribution to the success of the open source revolution, to the adoption of Linux-based operating systems, and to the success of open source users and the companies that supply them.'The interest in open source software development has grown enormously in the past year. This revised and expanded paperback edition includes new material on open source developments in 1999 and 2000. Raymond's clear and effective writing style accurately describing the benefits of open source software has been key to its success. With major vendors creating acceptance for open source within companies, independent vendors will become the open source story in 2001.", :img_url => "https://books.google.com.au/books?id=F6qgFtLwpJgC&printsec=frontcover&source=gbs_ge_summary_r&cad=0", :status => "Available"

book12 = Book.create :isbn => "9780132119177", :title => "The Pragmatic Programmer: From Journeyman to Master", :author => "Andrew Hunt, David Thomas", :publisher => "Addison-Wesley Professional", :date_published => "1999", :description => "Written as a series of self-contained sections and filled with entertaining anecdotes, thoughtful examples, and interesting analogies, The Pragmatic Programmer illustrates the best practices and major pitfalls of many different aspects of software development. Whether you're a new coder, an experienced programmer, or a manager responsible for software projects, use these lessons daily, and you'll quickly see improvements in personal productivity, accuracy, and job satisfaction. You'll learn skills and develop habits and attitudes that form the foundation for long-term success in your career. You'll become a Pragmatic Programmer.", :img_url => "https://books.google.com.au/books/content?id=5wBQEp6ruIAC&printsec=frontcover&img=1&zoom=1&edge=curl&imgtk=AFLRE71xvH7w5r35YI4PA3LKeAydOoka3VvNRtCUpNQ4JFxhOLPMfMJ4bkvYItWcvHGNafEJNgiJIIzw8wyIz_rkfMHo-PNWquCI4F4MHIRKUjwAZtbW-PFWILSl1yW7bkXssDKdnRnT", :status => "Available"

book13 = Book.create :isbn => "9780596555009", :title => "Learning the bash Shell: Unix Shell Programming", :author => "Cameron Newham", :publisher => "O'Reilly Media, Inc.", :date_published => "2005", :description => "O'Reilly's bestselling book on Linux's bash shell is at it again. Now that Linux is an established player both as a server and on the desktop Learning the bash Shell has been updated and refreshed to account for all the latest changes. Indeed, this third edition serves as the most valuable guide yet to the bash shell.As any good programmer knows, the first thing users of the Linux operating system come face to face with is the shell the UNIX term for a user interface to the system. In other words, it's what lets you communicate with the computer via the keyboard and display. Mastering the bash shell might sound fairly simple but it isn't. In truth, there are many complexities that need careful explanation, which is just what Learning the bash Shell provides.If you are new to shell programming, the book provides an excellent introduction, covering everything from the most basic to the most advanced features. And if you've been writing shell scripts for years, it offers a great way to find out what the new shell offers. Learning the bash Shell is also full of practical examples of shell commands and programs that will make everyday use of Linux that much easier.", :img_url => "https://books.google.com.au/books/content?id=dzBCH3x6fYEC&printsec=frontcover&img=1&zoom=1&edge=curl&imgtk=AFLRE734Wvh2Z0dr1buMw9FP8GtWugjbjHWg-yFgsHV9CjVqMABeEpvttKBPnFwtyRcItD5qyJ0yOhaerQV1TVQZydqjjJhOkhoCCrbGjFlLEqhluwvsto7vOrC015pp_27-2jz9Zti9", :status => "Available"

book14 = Book.create :isbn => "9780596555009", :title => "Learning the bash Shell: Unix Shell Programming", :author => "Cameron Newham", :publisher => "O'Reilly Media, Inc.", :date_published => "2005", :description => "O'Reilly's bestselling book on Linux's bash shell is at it again. Now that Linux is an established player both as a server and on the desktop Learning the bash Shell has been updated and refreshed to account for all the latest changes. Indeed, this third edition serves as the most valuable guide yet to the bash shell.As any good programmer knows, the first thing users of the Linux operating system come face to face with is the shell the UNIX term for a user interface to the system. In other words, it's what lets you communicate with the computer via the keyboard and display. Mastering the bash shell might sound fairly simple but it isn't. In truth, there are many complexities that need careful explanation, which is just what Learning the bash Shell provides.If you are new to shell programming, the book provides an excellent introduction, covering everything from the most basic to the most advanced features. And if you've been writing shell scripts for years, it offers a great way to find out what the new shell offers. Learning the bash Shell is also full of practical examples of shell commands and programs that will make everyday use of Linux that much easier.", :img_url => "https://books.google.com.au/books/content?id=dzBCH3x6fYEC&printsec=frontcover&img=1&zoom=1&edge=curl&imgtk=AFLRE734Wvh2Z0dr1buMw9FP8GtWugjbjHWg-yFgsHV9CjVqMABeEpvttKBPnFwtyRcItD5qyJ0yOhaerQV1TVQZydqjjJhOkhoCCrbGjFlLEqhluwvsto7vOrC015pp_27-2jz9Zti9", :status => "Available"

book13 = Book.create :isbn => "9780596555009", :title => "Learning the bash Shell: Unix Shell Programming", :author => "Cameron Newham", :publisher => "O'Reilly Media, Inc.", :date_published => "2005", :description => "O'Reilly's bestselling book on Linux's bash shell is at it again. Now that Linux is an established player both as a server and on the desktop Learning the bash Shell has been updated and refreshed to account for all the latest changes. Indeed, this third edition serves as the most valuable guide yet to the bash shell.As any good programmer knows, the first thing users of the Linux operating system come face to face with is the shell the UNIX term for a user interface to the system. In other words, it's what lets you communicate with the computer via the keyboard and display. Mastering the bash shell might sound fairly simple but it isn't. In truth, there are many complexities that need careful explanation, which is just what Learning the bash Shell provides.If you are new to shell programming, the book provides an excellent introduction, covering everything from the most basic to the most advanced features. And if you've been writing shell scripts for years, it offers a great way to find out what the new shell offers. Learning the bash Shell is also full of practical examples of shell commands and programs that will make everyday use of Linux that much easier.", :img_url => "https://books.google.com.au/books/content?id=dzBCH3x6fYEC&printsec=frontcover&img=1&zoom=1&edge=curl&imgtk=AFLRE734Wvh2Z0dr1buMw9FP8GtWugjbjHWg-yFgsHV9CjVqMABeEpvttKBPnFwtyRcItD5qyJ0yOhaerQV1TVQZydqjjJhOkhoCCrbGjFlLEqhluwvsto7vOrC015pp_27-2jz9Zti9", :status => "Available"

book14 = Book.create :isbn => "9780596555009", :title => "Learning the bash Shell: Unix Shell Programming", :author => "Cameron Newham", :publisher => "O'Reilly Media, Inc.", :date_published => "2005", :description => "O'Reilly's bestselling book on Linux's bash shell is at it again. Now that Linux is an established player both as a server and on the desktop Learning the bash Shell has been updated and refreshed to account for all the latest changes. Indeed, this third edition serves as the most valuable guide yet to the bash shell.As any good programmer knows, the first thing users of the Linux operating system come face to face with is the shell the UNIX term for a user interface to the system. In other words, it's what lets you communicate with the computer via the keyboard and display. Mastering the bash shell might sound fairly simple but it isn't. In truth, there are many complexities that need careful explanation, which is just what Learning the bash Shell provides.If you are new to shell programming, the book provides an excellent introduction, covering everything from the most basic to the most advanced features. And if you've been writing shell scripts for years, it offers a great way to find out what the new shell offers. Learning the bash Shell is also full of practical examples of shell commands and programs that will make everyday use of Linux that much easier.", :img_url => "https://books.google.com.au/books/content?id=dzBCH3x6fYEC&printsec=frontcover&img=1&zoom=1&edge=curl&imgtk=AFLRE734Wvh2Z0dr1buMw9FP8GtWugjbjHWg-yFgsHV9CjVqMABeEpvttKBPnFwtyRcItD5qyJ0yOhaerQV1TVQZydqjjJhOkhoCCrbGjFlLEqhluwvsto7vOrC015pp_27-2jz9Zti9", :status => "Available"

book15 = Book.create :isbn => "9781593275846", :title => "Eloquent JavaScript, 2nd Ed.: A Modern Introduction to Programming", :author => "Marijn Haverbeke", :publisher => "No Starch Press", :date_published => "2014", :description => "JavaScript lies at the heart of almost every modern web application, from social apps to the newest browser-based games. Though simple for beginners to pick up and play with, JavaScript is a flexible, complex language that you can use to build full-scale applications.

Eloquent JavaScript, 2nd Edition dives deep into the JavaScript language to show you how to write beautiful, effective code. Author Marijn Haverbeke immerses you in example code from the start, while exercises and full-chapter projects give you hands-on experience with writing your own programs. As you build projects such as an artificial life simulation, a simple programming language, and a paint program, you’ll learn:

The essential elements of programming, including syntax, control, and dataHow to organize and clarify your code with object-oriented and functional programming techniquesHow to script the browser and make basic web applicationsHow to use the DOM effectively to interact with browsersHow to harness Node.js to build servers and utilities
This edition is thoroughly revised and modernized to reflect the current state of Java­Script and web browsers, with brand-new material, such as a chapter on code performance in Java­Script, and expanded coverage of recursion and closures. All source code is available online in an inter­active sandbox, where you can edit the code, run it, and see its output instantly.

Isn’t it time you became fluent in the language of the Web?", :img_url => "https://books.google.com.au/books/content?id=mDzDBQAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&imgtk=AFLRE71R62maBYwjn9bqp4oZ6pqWX04EhGSQvGOZepbBJvNZsS6UCeZptryJMp6n4aTcmi97VpXvd7AO3GbOwm--P-3iJZrsfDSQBaqid1qU7R7k8BoasMnTRcRyKcZ48HQW6cGazZWW", :status => "Available"

book16 = Book.create :isbn => "9781593275846", :title => "Eloquent JavaScript, 2nd Ed.: A Modern Introduction to Programming", :author => "Marijn Haverbeke", :publisher => "No Starch Press", :date_published => "2014", :description => "JavaScript lies at the heart of almost every modern web application, from social apps to the newest browser-based games. Though simple for beginners to pick up and play with, JavaScript is a flexible, complex language that you can use to build full-scale applications.

Eloquent JavaScript, 2nd Edition dives deep into the JavaScript language to show you how to write beautiful, effective code. Author Marijn Haverbeke immerses you in example code from the start, while exercises and full-chapter projects give you hands-on experience with writing your own programs. As you build projects such as an artificial life simulation, a simple programming language, and a paint program, you’ll learn:

The essential elements of programming, including syntax, control, and dataHow to organize and clarify your code with object-oriented and functional programming techniquesHow to script the browser and make basic web applicationsHow to use the DOM effectively to interact with browsersHow to harness Node.js to build servers and utilities
This edition is thoroughly revised and modernized to reflect the current state of Java­Script and web browsers, with brand-new material, such as a chapter on code performance in Java­Script, and expanded coverage of recursion and closures. All source code is available online in an inter­active sandbox, where you can edit the code, run it, and see its output instantly.

Isn’t it time you became fluent in the language of the Web?", :img_url => "https://books.google.com.au/books/content?id=mDzDBQAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&imgtk=AFLRE71R62maBYwjn9bqp4oZ6pqWX04EhGSQvGOZepbBJvNZsS6UCeZptryJMp6n4aTcmi97VpXvd7AO3GbOwm--P-3iJZrsfDSQBaqid1qU7R7k8BoasMnTRcRyKcZ48HQW6cGazZWW", :status => "Available"

book17 = Book.create :isbn => "9781118531648", :title => "JavaScript and JQuery: Interactive Front-End Web Development", :author => "Jon Duckett", :publisher => "John Wiley & Sons", :date_published => "2014", :description => "This full-color book adopts a visual approach to teaching JavaScript & jQuery, showing you how to make web pages more interactive and interfaces more intuitive through the use of inspiring code examples, infographics, and photography. The content assumes no previous programming experience, other than knowing how to create a basic web page in HTML & CSS. You'll learn how to achieve techniques seen on many popular websites (such as adding animation, tabbed panels, content sliders, form validation, interactive galleries, and sorting data)..

Introduces core programming concepts in JavaScript and jQuery
Uses clear descriptions, inspiring examples, and easy-to-follow diagrams
Teaches you how to create scripts from scratch, and understand the thousands of JavaScripts, JavaScript APIs, and jQuery plugins that are available on the web
Demonstrates the latest practices in progressive enhancement, cross-browser compatibility, and when you may be better off using CSS3
If you're looking to create more enriching web experiences and express your creativity through code, then this is the book for you.", :img_url => "https://books.google.com.au/books/content?id=LpctBAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&imgtk=AFLRE72_Sda17lxYZZqfaVXZn4weIePShYTfwRxT0H0IwZNv69LHwBjZcFDUHQrSsJe5SADOcI9XXoggru6qCJxqdEdt1DCIO9-X2YZFwS9zLEyWJE3-9YsJ_yJ9z8aDTb_dx3bNTiZJ", :status => "Available"

book18 = Book.create :isbn => "9781593275853", :title => "If Hemingway Wrote JavaScript", :author => "Angus Croll", :publisher => "No Starch Press", :date_published => "2014", :description => "What if William Shakespeare were asked to generate the Fibonacci series or Jane Austen had to write a factorial program? In If Hemingway Wrote JavaScript, author Angus Croll imagines short JavaScript programs as written by famous wordsmiths. The result is a peculiar and charming combination of prose, poetry, and programming.

The best authors are those who obsess about language—and the same goes for JavaScript developers. To master either craft, you must experiment with language to develop your own style, your own idioms, and your own expressions. To that end, If Hemingway Wrote JavaScript playfully bridges the worlds of programming and literature for the literary geek in all of us.", :img_url => "https://books.google.com.au/books/content?id=JktNBQAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&imgtk=AFLRE73bqg5nbcj693jQrxColA6yyRBCQST6pglyHfRNynTumDO3YadHD5QiW7SD6c9K0ZlFq881nv9jSacd9pnEKVfS3Xl0RWkzXCiczoV954dgGn_7idnqDyfUsGfNaqV43eUi_-Sd", :status => "Available"

book19 = Book.create :isbn => "9781118206911", :title => "HTML and CSS: Design and Build Websites", :author => "Jon Duckett", :publisher => "John Wiley & Sons", :date_published => "2011", :description => "Every day, more and more people want to learn some HTML and CSS. Joining the professional web designers and programmers are new audiences who need to know a little bit of code at work (update a content management system or e-commerce store) and those who want to make their personal blogs more attractive. Many books teaching HTML and CSS are dry and only written for those who want to become programmers, which is why this book takes an entirely new approach.

Introduces HTML and CSS in a way that makes them accessible to everyone—hobbyists, students, and professionals—and it’s full-color throughout
Utilizes information graphics and lifestyle photography to explain the topics in a simple way that is engaging
Boasts a unique structure that allows you to progress through the chapters from beginning to end or just dip into topics of particular interest at your leisure
This educational book is one that you will enjoy picking up, reading, then referring back to. It will make you wish other technical topics were presented in such a simple, attractive and engaging way!", :img_url => "https://books.google.com.au/books/content?id=blCyf8XF41sC&printsec=frontcover&img=1&zoom=1&edge=curl&imgtk=AFLRE71t1c003Z92xpIkuW-EJN_PvKrYY_KYdw6Ppzqw_wGLKFl9uTSMMNT6KVp9CCb3dgtWTsk6Ki1y6u4w49i7trpUzImzCs9AcRZr36Z37Im-AeCpxFUYnDY34nCbop0lYPZKtBTA", :status => "Available"

book20 = Book.create :isbn => "9781118206911", :title => "HTML and CSS: Design and Build Websites", :author => "Jon Duckett", :publisher => "John Wiley & Sons", :date_published => "2011", :description => "Every day, more and more people want to learn some HTML and CSS. Joining the professional web designers and programmers are new audiences who need to know a little bit of code at work (update a content management system or e-commerce store) and those who want to make their personal blogs more attractive. Many books teaching HTML and CSS are dry and only written for those who want to become programmers, which is why this book takes an entirely new approach.

Introduces HTML and CSS in a way that makes them accessible to everyone—hobbyists, students, and professionals—and it’s full-color throughout
Utilizes information graphics and lifestyle photography to explain the topics in a simple way that is engaging
Boasts a unique structure that allows you to progress through the chapters from beginning to end or just dip into topics of particular interest at your leisure
This educational book is one that you will enjoy picking up, reading, then referring back to. It will make you wish other technical topics were presented in such a simple, attractive and engaging way!", :img_url => "https://books.google.com.au/books/content?id=blCyf8XF41sC&printsec=frontcover&img=1&zoom=1&edge=curl&imgtk=AFLRE71t1c003Z92xpIkuW-EJN_PvKrYY_KYdw6Ppzqw_wGLKFl9uTSMMNT6KVp9CCb3dgtWTsk6Ki1y6u4w49i7trpUzImzCs9AcRZr36Z37Im-AeCpxFUYnDY34nCbop0lYPZKtBTA", :status => "Available"

book21 = Book.create :isbn => "9781430219484", :title => "Coders at Work: Reflections on the Craft of Programming", :author => "Peter Seibel", :publisher => "Apress", :date_published => "2009", :description => "Peter Seibel interviews 15 of the most interesting computer programmers alive today in Coders at Work, offering a companion volume to Apress’s highly acclaimed best-seller Founders at Work by Jessica Livingston. As the words “at work” suggest, Peter Seibel focuses on how his interviewees tackle the day-to-day work of programming, while revealing much more, like how they became great programmers, how they recognize programming talent in others, and what kinds of problems they find most interesting.

Hundreds of people have suggested names of programmers to interview on the Coders at Work web site: www.codersatwork.com. The complete list was 284 names. Having digested everyone’s feedback, we selected 15 folks who’ve been kind enough to agree to be interviewed:

Frances Allen: Pioneer in optimizing compilers, first woman to win the Turing Award (2006) and first female IBM fellow Joe Armstrong: Inventor of Erlang Joshua Bloch: Author of the Java collections framework, now at Google Bernie Cosell: One of the main software guys behind the original ARPANET IMPs and a master debugger Douglas Crockford: JSON founder, JavaScript architect at Yahoo! L. Peter Deutsch: Author of Ghostscript, implementer of Smalltalk-80 at Xerox PARC and Lisp 1.5 on PDP-1 Brendan Eich: Inventor of JavaScript, CTO of the Mozilla Corporation Brad Fitzpatrick: Writer of LiveJournal, OpenID, memcached, and Perlbal Dan Ingalls: Smalltalk implementor and designer Simon Peyton Jones: Coinventor of Haskell and lead designer of Glasgow Haskell Compiler Donald Knuth: Author of The Art of Computer Programming and creator of TeX Peter Norvig: Director of Research at Google and author of the standard text on AI Guy Steele: Coinventor of Scheme and part of the Common Lisp Gang of Five, currently working on Fortress Ken Thompson: Inventor of UNIX Jamie Zawinski: Author of XEmacs and early Netscape/Mozilla hacker What you’ll learnHow the best programmers in the world do their jobs! Who this book is for
Programmers interested in the point of view of leaders in the field. Programmers looking for approaches that work for some of these outstanding programmers.", :img_url => "https://books.google.com.au/books/content?id=nneBa6-mWfgC&printsec=frontcover&img=1&zoom=1&edge=curl&imgtk=AFLRE72Alirb9Qo2qn7ashzl3dcFZ_Ke_woZuKFJZ8XV3owI40hQSqye-vCmcF8dZSy1feNFIPeoIFER6Pfvd9dRsOpasuj4kPAfuCEXgCZKiY6LMJYnF6gB9s10lPF1u6HMrPS1P37r", :status => "Available"



User.destroy_all

user1 = User.create :name => 'Hayley Petrov', :admin => true, :email => 'hayley@ga.co', :password => 'chicken', :password_confirmation => 'chicken'

user2 = User.create :name => 'Daniel Ting', :admin => false, :email => 'dting@ga.co', :password => 'chicken', :password_confirmation => 'chicken'

user3 = User.create :name => 'Christle Lee', :admin => false, :email => 'clee@ga.co', :password => 'chicken', :password_confirmation => 'chicken'

user4 = User.create :name => 'Daniele Peviani', :admin => false, :email => 'dpeviani@ga.co', :password => 'chicken', :password_confirmation => 'chicken'


Reservation.destroy_all


Request.destroy_all

user4.requests.create :isbn => '9781491901946'
user2.requests.create :isbn => '9780596158002'
user3.requests.create :isbn => '9781933820248'

PendingItem.destroy_all
