Book.destroy_all

book1 = Book.create :isbn => "9781680501711", :title => "Agile Web Development with Rails 5", :author => "Sam Ruby", :publisher => "Pragmatic Bookshelf", :date_published => "2016", :description => "Rails 5 and Ruby 2.2 bring many improvements, including new APIs and substantial performance enhancements, and the fifth edition of this award-winning classic is now updated! If you're new to Rails, you'll get step-by-step guidance. If you're an experienced developer, this book will give you the comprehensive, insider information you need for the latest version of Ruby on Rails.", :img_url => "https://books.google.com.au/books/content?id=ySyjDAEACAAJ&printsec=frontcover&img=1&zoom=1&imgtk=AFLRE729ScXGYBwXdU9pD35pCjFtTrvPr0yxmBV3kEWosixhChOoRI7l9jUhQPxQIy2Zt8qmz9nwDTs988X_hRqIUttT-DtKwHIOu56JYo1p5_C_jdUJDHwaMTW3nqTE8a7zzTRvVmZT", :status => "available"

book2 = Book.create :isbn => "9781680501711", :title => "Agile Web Development with Rails 5", :author => "Sam Ruby", :publisher => "Pragmatic Bookshelf", :date_published => "2016", :description => "Rails 5 and Ruby 2.2 bring many improvements, including new APIs and substantial performance enhancements, and the fifth edition of this award-winning classic is now updated! If you're new to Rails, you'll get step-by-step guidance. If you're an experienced developer, this book will give you the comprehensive, insider information you need for the latest version of Ruby on Rails.", :img_url => "https://books.google.com.au/books/content?id=ySyjDAEACAAJ&printsec=frontcover&img=1&zoom=1&imgtk=AFLRE729ScXGYBwXdU9pD35pCjFtTrvPr0yxmBV3kEWosixhChOoRI7l9jUhQPxQIy2Zt8qmz9nwDTs988X_hRqIUttT-DtKwHIOu56JYo1p5_C_jdUJDHwaMTW3nqTE8a7zzTRvVmZT", :status => "available"

book3 = Book.create :isbn => "9781449360788", :title => "Functional JavaScript: Introducing Functional Programming with Underscore.js", :author => "Michael Fogus", :publisher => "O'Reilly Media, Inc.", :date_published => "2013", :description => "How can you overcome JavaScript language oddities and unsafe features? With this book, you’ll learn how to create code that’s beautiful, safe, and simple to understand and test by using JavaScript’s functional programming support. Author Michael Fogus shows you how to apply functional-style concepts with Underscore.js, a JavaScript library that facilitates functional programming techniques.", :img_url => "https://books.google.com.au/books/content?id=OIhuxqUO2TcC&printsec=frontcover&img=1&zoom=1&edge=curl&imgtk=AFLRE721GnXpSp8NirRfuVs4OaobKc8fL5o_Js3IJyF0zzC_43CxECpSFVbMlocSgBgFZZ6PRR8UJU7UqUlt5P8ekq7Hj8J7YR4yWCIg07n7_7btBC4B80ZO_AhHVNQfihhfHeC07u2e", :status => "available"

book4 = Book.create :isbn => "9781449360788", :title => "Functional JavaScript: Introducing Functional Programming with Underscore.js", :author => "Michael Fogus", :publisher => "O'Reilly Media, Inc.", :date_published => "2013", :description => "How can you overcome JavaScript language oddities and unsafe features? With this book, you’ll learn how to create code that’s beautiful, safe, and simple to understand and test by using JavaScript’s functional programming support. Author Michael Fogus shows you how to apply functional-style concepts with Underscore.js, a JavaScript library that facilitates functional programming techniques.", :img_url => "https://books.google.com.au/books/content?id=OIhuxqUO2TcC&printsec=frontcover&img=1&zoom=1&edge=curl&imgtk=AFLRE721GnXpSp8NirRfuVs4OaobKc8fL5o_Js3IJyF0zzC_43CxECpSFVbMlocSgBgFZZ6PRR8UJU7UqUlt5P8ekq7Hj8J7YR4yWCIg07n7_7btBC4B80ZO_AhHVNQfihhfHeC07u2e", :status => "available"

book5 = Book.create :isbn => "9780262560993", :title => "The Little Schemer", :author => "Daniel P. Friedman, Matthias Felleisen", :publisher => "MIT Press", :date_published => "1996", :description => "I learned more about LISP from this book than I have from any of the other LISP books I've read over the years. . . . While other books will tell you the mechanics of LISP, they can leave you largely uninformed on the style of problem-solving for which LISP is optimized. The Little LISPer teaches you how to think in the LISP language. . . an inexpensive, enjoyable introduction.", :img_url => "https://books.google.com.au/books/content?id=xyO-KLexVnMC&printsec=frontcover&img=1&zoom=1&edge=curl&imgtk=AFLRE73d6HD3Nf6Sc5t8MR-J3zLZBQvczJUHf0ywNZsfiQTgh3sFLPIg9RAu8LG5BKLOVZG5NgzodS4wWbTVCiqZv81KwI8c3alOgqwcPHYag_3Z-NcQ1xpaOTnsYnzfiObMgbDFMGdw", :status => "available"

book6 = Book.create :isbn => "9780262560993", :title => "The Little Schemer", :author => "Daniel P. Friedman, Matthias Felleisen", :publisher => "MIT Press", :date_published => "1996", :description => "I learned more about LISP from this book than I have from any of the other LISP books I've read over the years. . . . While other books will tell you the mechanics of LISP, they can leave you largely uninformed on the style of problem-solving for which LISP is optimized. The Little LISPer teaches you how to think in the LISP language. . . an inexpensive, enjoyable introduction.", :img_url => "https://books.google.com.au/books/content?id=xyO-KLexVnMC&printsec=frontcover&img=1&zoom=1&edge=curl&imgtk=AFLRE73d6HD3Nf6Sc5t8MR-J3zLZBQvczJUHf0ywNZsfiQTgh3sFLPIg9RAu8LG5BKLOVZG5NgzodS4wWbTVCiqZv81KwI8c3alOgqwcPHYag_3Z-NcQ1xpaOTnsYnzfiObMgbDFMGdw", :status => "available"

book7 = Book.create :isbn => "9780199724574", :title => "Complexity: A Guided Tour", :author => "Melanie Mitchell", :publisher => "Oxford University Press", :date_published => "2009", :description => "What enables individually simple insects like ants to act with such precision and purpose as a group? How do trillions of neurons produce something as extraordinarily complex as consciousness? In this remarkably clear and companionable book, leading complex systems scientist Melanie Mitchell provides an intimate tour of the sciences of complexity, a broad set of efforts that seek to explain how large-scale complex, organized, and adaptive behavior can emerge from simple interactions among myriad individuals. Based on her work at the Santa Fe Institute and drawing on its interdisciplinary strategies, Mitchell brings clarity to the workings of complexity across a broad range of biological, technological, and social phenomena, seeking out the general principles or laws that apply to all of them. Richly illustrated, Complexity: A Guided Tour--winner of the 2010 Phi Beta Kappa Book Award in Science--offers a wide-ranging overview of the ideas underlying complex systems science, the current research at the forefront of this field, and the prospects for its contribution to solving some of the most important scientific questions of our time.", :img_url => "https://books.google.com.au/books/content?id=j-PQCwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&imgtk=AFLRE72GQGKtr7vZ3In6YvL5BtCM9g6hKrWlkdZesAADgoOZqYesEjoJtGJIFlKLUuhGa-qxPa4VQ_YZe9f-rKzJVWfq8q6crb4XgguoKG6NU8E-Iux2ttoUUXvNYh1BXlndFVSWVLwc", :status => "available"

book8 = Book.create :isbn => "9780199724574", :title => "Complexity: A Guided Tour", :author => "Melanie Mitchell", :publisher => "Oxford University Press", :date_published => "2009", :description => "What enables individually simple insects like ants to act with such precision and purpose as a group? How do trillions of neurons produce something as extraordinarily complex as consciousness? In this remarkably clear and companionable book, leading complex systems scientist Melanie Mitchell provides an intimate tour of the sciences of complexity, a broad set of efforts that seek to explain how large-scale complex, organized, and adaptive behavior can emerge from simple interactions among myriad individuals. Based on her work at the Santa Fe Institute and drawing on its interdisciplinary strategies, Mitchell brings clarity to the workings of complexity across a broad range of biological, technological, and social phenomena, seeking out the general principles or laws that apply to all of them. Richly illustrated, Complexity: A Guided Tour--winner of the 2010 Phi Beta Kappa Book Award in Science--offers a wide-ranging overview of the ideas underlying complex systems science, the current research at the forefront of this field, and the prospects for its contribution to solving some of the most important scientific questions of our time.", :img_url => "https://books.google.com.au/books/content?id=j-PQCwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&imgtk=AFLRE72GQGKtr7vZ3In6YvL5BtCM9g6hKrWlkdZesAADgoOZqYesEjoJtGJIFlKLUuhGa-qxPa4VQ_YZe9f-rKzJVWfq8q6crb4XgguoKG6NU8E-Iux2ttoUUXvNYh1BXlndFVSWVLwc", :status => "available"

book9 = Book.create :isbn => "9780140289206", :title => "Gödel, Escher, Bach: An Eternal Golden Braid", :author => "Douglas R. Hofstadter", :publisher => "Penguin", :date_published => "2000", :description => "'What is a self, and how can a self come out of inaminate matter?' This is the riddle that drove Hofstadter to write this extraordinary book. Linking together the music of J.S. Bach, the graphic art of Escher and the mathematical theorems of Godel, as well as ideas drawn from logic, biology, psychology, physics and linguistics, Douglas Hofstadter illuminates one of the greatest mysteries of modern science: the nature of human thought processes. 'Every few decades an unknown author brings outa book of such depth, clarity, range, wit, beauty and originality that it is recognized at once as a major literary event. This is such a work' - Martin Gardner", :img_url => "https://books.google.com.au/books/content?id=grzEQgAACAAJ&printsec=frontcover&img=1&zoom=1&imgtk=AFLRE70UMZ4zDjpe_E_KWiSRbqQsEv6t1ixKE4jSDIXy6rYoipTxRcpPnMUDOoaJQpeNzS0jJSPuLGAosQAsJ1ZWNSf7-fWql3q-WKotp0GGoLsEgxTXlgVL4ADqLbuX5fqc9XHGSxLV", :status => "available"

book10 = Book.create :isbn => "9780140289206", :title => "Gödel, Escher, Bach: An Eternal Golden Braid", :author => "Douglas R. Hofstadter", :publisher => "Penguin", :date_published => "2000", :description => "'What is a self, and how can a self come out of inaminate matter?' This is the riddle that drove Hofstadter to write this extraordinary book. Linking together the music of J.S. Bach, the graphic art of Escher and the mathematical theorems of Godel, as well as ideas drawn from logic, biology, psychology, physics and linguistics, Douglas Hofstadter illuminates one of the greatest mysteries of modern science: the nature of human thought processes. 'Every few decades an unknown author brings outa book of such depth, clarity, range, wit, beauty and originality that it is recognized at once as a major literary event. This is such a work' - Martin Gardner", :img_url => "https://books.google.com.au/books/content?id=grzEQgAACAAJ&printsec=frontcover&img=1&zoom=1&imgtk=AFLRE70UMZ4zDjpe_E_KWiSRbqQsEv6t1ixKE4jSDIXy6rYoipTxRcpPnMUDOoaJQpeNzS0jJSPuLGAosQAsJ1ZWNSf7-fWql3q-WKotp0GGoLsEgxTXlgVL4ADqLbuX5fqc9XHGSxLV", :status => "available"

book11 = Book.create :isbn => "9780596554873", :title => "JavaScript: The Good Parts: The Good Parts", :author => "Douglas Crockford", :publisher => "O'Reilly Media, Inc.", :date_published => "2008", :description => "Most programming languages contain good and bad parts, but JavaScript has more than its share of the bad, having been developed and released in a hurry before it could be refined. This authoritative book scrapes away these bad features to reveal a subset of JavaScript that's more reliable, readable, and maintainable than the language as a whole—a subset you can use to create truly extensible and efficient code.", :img_url => "https://books.google.com.au/books/content?id=PXa2bby0oQ0C&printsec=frontcover&img=1&zoom=1&edge=curl&imgtk=AFLRE722AjJE15txFoKk8pu6d8BqpOAtMzMYyBUMd0SDVtn8Jstl5aKnkWL_OxWTN4rvIRdV09Di86Hi7FihqESw8b8g2RDkG62dOK1uws50LCCm7Fx4NbtHk-A2yykhsYoTkpUA2CUf", :status => "available"

book12 = Book.create :isbn => "9780596554873", :title => "JavaScript: The Good Parts: The Good Parts", :author => "Douglas Crockford", :publisher => "O'Reilly Media, Inc.", :date_published => "2008", :description => "Most programming languages contain good and bad parts, but JavaScript has more than its share of the bad, having been developed and released in a hurry before it could be refined. This authoritative book scrapes away these bad features to reveal a subset of JavaScript that's more reliable, readable, and maintainable than the language as a whole—a subset you can use to create truly extensible and efficient code.", :img_url => "https://books.google.com.au/books/content?id=PXa2bby0oQ0C&printsec=frontcover&img=1&zoom=1&edge=curl&imgtk=AFLRE722AjJE15txFoKk8pu6d8BqpOAtMzMYyBUMd0SDVtn8Jstl5aKnkWL_OxWTN4rvIRdV09Di86Hi7FihqESw8b8g2RDkG62dOK1uws50LCCm7Fx4NbtHk-A2yykhsYoTkpUA2CUf", :status => "available"

book13 = Book.create :isbn => "9781593277574", :title => "Understanding ECMAScript 6: The Definitive Guide for JavaScript Developers", :author => "Nicholas C. Zakas", :publisher => "No Starch Press", :date_published => "2016", :description => "ECMAScript 6 represents the biggest update to the core of JavaScript in the history of the language. In Understanding ECMAScript 6, expert developer Nicholas C. Zakas provides a complete guide to the object types, syntax, and other exciting changes that ECMAScript 6 brings to JavaScript. Every chapter is packed with example code that works in any JavaScript environment so you’ll be able to see new features in action. You’ll learn:

*How ECMAScript 6 class syntax relates to more familiar JavaScript concepts
*What makes iterators and generators useful
*How arrow functions differ from regular functions
*Ways to store data with sets, maps, and more
*The power of inheritance
*How to improve asynchronous programming with promises
*How modules change the way you organize code

Whether you’re a web developer or a Node.js developer, you’ll find Understanding ECMAScript 6 indispensable on your journey from ECMAScript 5 to ECMAScript 6.", :img_url => "https://books.google.com.au/books/content?id=6Ze7DQAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&imgtk=AFLRE719CxgfhmfZyupAvuHOckLJNZNPACU9WKXZJfpngC0xfzru7uzFTW-7uPtiGrT7AguHjmE2WmJp3Mx2Vq0Y6-b9HmA9C1co_EUi0mdI5JhVYD0VKIJK4k2DSv9-z61qd3A8mJLg", :status => "available"

book14 = Book.create :isbn => "9781593277574", :title => "Understanding ECMAScript 6: The Definitive Guide for JavaScript Developers", :author => "Nicholas C. Zakas", :publisher => "No Starch Press", :date_published => "2016", :description => "ECMAScript 6 represents the biggest update to the core of JavaScript in the history of the language. In Understanding ECMAScript 6, expert developer Nicholas C. Zakas provides a complete guide to the object types, syntax, and other exciting changes that ECMAScript 6 brings to JavaScript. Every chapter is packed with example code that works in any JavaScript environment so you’ll be able to see new features in action. You’ll learn:

*How ECMAScript 6 class syntax relates to more familiar JavaScript concepts
*What makes iterators and generators useful
*How arrow functions differ from regular functions
*Ways to store data with sets, maps, and more
*The power of inheritance
*How to improve asynchronous programming with promises
*How modules change the way you organize code

Whether you’re a web developer or a Node.js developer, you’ll find Understanding ECMAScript 6 indispensable on your journey from ECMAScript 5 to ECMAScript 6.", :img_url => "https://books.google.com.au/books/content?id=6Ze7DQAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&imgtk=AFLRE719CxgfhmfZyupAvuHOckLJNZNPACU9WKXZJfpngC0xfzru7uzFTW-7uPtiGrT7AguHjmE2WmJp3Mx2Vq0Y6-b9HmA9C1co_EUi0mdI5JhVYD0VKIJK4k2DSv9-z61qd3A8mJLg", :status => "available"

User.destroy_all

user1 = User.create :name => 'Hayley Petrov', :admin => true, :course => 'staff', :email => 'hayley@ga.co', :password => 'chicken', :password_confirmation => 'chicken'

user2 = User.create :name => 'Daniel Ting', :admin => false, :course => 'WDI19', :email => 'dting@ga.co', :password => 'chicken', :password_confirmation => 'chicken'

user3 = User.create :name => 'Christle Lee', :admin => false, :course => 'WDI19', :email => 'clee@ga.co', :password => 'chicken', :password_confirmation => 'chicken'

user4 = User.create :name => 'Daniele Peviani', :admin => false, :course => 'WDI19', :email => 'dpeviani@ga.co', :password => 'chicken', :password_confirmation => 'chicken'


Reservation.destroy_all

# user2.reservations.create :book_id => book2.id, :date_requested => '2017-02-09', :date_borrowed => '2017-02-10', :date_due => '2017-02-20'
#
# user3.reservations.create :book_id => book3.id, :date_requested => '2017-02-10', :date_borrowed => '', :date_due => ''


Request.destroy_all

user4.requests.create :isbn => '9781491901946'
user2.requests.create :isbn => '9780596158002'
user3.requests.create :isbn => '9781933820248'

PendingItem.destroy_all
